---
# Source: opensearch/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "opensearch-data"
  namespace: opensearch
  labels:
    helm.sh/chart: opensearch-1.2.5
    app.kubernetes.io/name: opensearch-data
    app.kubernetes.io/instance: alochym-data
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: opensearch-data
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opensearch-data
      app.kubernetes.io/instance: alochym-data
